Finished
slava-moiseev-kramatorsk/spring_boot_intro pull request #10
Opened 2024-08-16 15:06 UTC by slava-moiseev-kramatorsk

Зіштовхнувся з одніею проблемкою- створив юзера через файл 08-insert-admin-in-users-table.yaml задав пароль, звісно. Все компілюеться -працює(мабудь) бо я не можу підключитися через ПостМан пароль захешовано і не знаю де та як тепер цей хеш знайти для входу.  ось ,що консоль видала  : Encoded password does not look like BCrypt.

2024-08-16 15:12 UTC, slava-moiseev-kramatorsk commented
Ну взагалі то цікава задачка, я чьомусь вирішив що в табліці users має бути колонка role_id. створив, виявилось що марно, адже є users_roles. видали, відкатити, вона пов'язана з users_roles так просто не відалишь...  ще й з databasechangeLog також. так собі квест.....

2024-08-17 08:06 UTC, Elena-Bruyako requested changes
see comments

2024-08-17 08:06 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/security/CustomUserDetailsService.java
> +                        () -> new UsernameNotFoundException("Can`t find by this email" + email));
```suggestion
                        () -> new EntityNotFoundException("Can`t find by this email" + email));
```

2024-08-17 08:06 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/security/CustomUserDetailsService.java
> +    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String email) {
```

2024-08-17 08:06 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/repository/user/UserRepository.java
> +    Optional<User> findByEmail(String email);
```suggestion
    @EntityGraph(attributePaths = "roles")
    Optional<User> findByEmail(String email);
```

2024-08-17 08:19 UTC, slava-moiseev-kramatorsk commented on src/main/java/com/example/demo/repository/user/UserRepository.java
> +    Optional<User> findByEmail(String email);
ааа дійсно, дійсно.  lazy...

2024-08-19 18:40 UTC, sarakhmen approved these changes

2024-08-20 07:18 UTC, Elena-Bruyako approved these changes

2024-08-20 17:50 UTC, merged