Finished
slava-moiseev-kramatorsk/spring_boot_intro pull request #12
Opened 2024-08-25 16:22 UTC by slava-moiseev-kramatorsk

2024-08-26 13:34 UTC, Elena-Bruyako requested changes
see comments

2024-08-26 13:34 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```

2024-08-26 13:34 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/service/book/BookServiceImpl.java
> +    @Override
add also book.setCategories in save and update method for book

2024-08-26 15:58 UTC, slava-moiseev-kramatorsk commented on src/main/java/com/example/demo/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
Don't forget to exclude entity fields from toString(), equals(), and hashCode() methods. Example:

  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(
    name = "book_category",
    joinColumns = @JoinColumn(name = "book_id"),
    inverseJoinColumns = @JoinColumn(name = "category_id"))
  @ToString.Exclude
  @EqualsAndHashCode.Exclude
  private Set<Category> categories = new HashSet<>();
  
  Це в описі завдання. Тому і залишив (fetch = FetchType.LAZY)

2024-08-26 15:58 UTC, slava-moiseev-kramatorsk commented on src/main/java/com/example/demo/service/book/BookServiceImpl.java
> +    @Override
Доброго. А я думав, що book.setCategories виконуеться в BookMapper і не важливо який метод його викликає чи то save, чи то update.

2024-08-28 10:55 UTC, MentorMateAcademy approved these changes

2024-08-31 07:31 UTC, merged