Finished, try1
slava-moiseev-kramatorsk/spring_boot_intro pull request #16
Opened 2024-11-07 20:25 UTC by slava-moiseev-kramatorsk

2024-11-09 11:55 UTC, slava-moiseev-kramatorsk commented
![image](https://github.com/user-attachments/assets/d00a9a91-a7fd-42dd-ab3a-7b486c4f3537)
![image](https://github.com/user-attachments/assets/c51f3885-729d-4d11-972f-6ce21bed817e)
![image](https://github.com/user-attachments/assets/4dc18598-66ca-4875-814e-0cd3faed9a8a)
![image](https://github.com/user-attachments/assets/b85ccf05-0914-44c9-83cd-e5fe2de81d39)

2024-11-09 11:58 UTC, slava-moiseev-kramatorsk commented
Стосовно BookServiceTest.  line 118 List<BookDto> actual з використанням "final". Якщо без нього мені чекСтайл ругаеться.
![image](https://github.com/user-attachments/assets/4b231284-ae4a-4fb9-80a7-139d62cd0a87)

2024-11-11 15:22 UTC, Elena-Bruyako requested changes
see comments

2024-11-11 15:22 UTC, Elena-Bruyako commented on .env
> +MYSQLDB_ROOT_PASSWORD=rfrfirf
.env file shouldn't be stored in git
remove it and create .env.sample without values

2024-11-11 15:22 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Category.java
> +    public Category() {
use Lombok annotation instead of generating no args constructor

2024-11-11 15:22 UTC, Elena-Bruyako commented on src/test/java/com/example/demo/controller/BookControllerTest.java
> +
remove empty line after class declaration
check other places

2024-11-11 15:22 UTC, Elena-Bruyako commented on src/test/java/com/example/demo/controller/BookControllerTest.java
> +@Transactional
why do you need this annotation here?

2024-11-11 15:22 UTC, Elena-Bruyako commented on src/test/java/com/example/demo/controller/BookControllerTest.java
> +                    new ClassPathResource("database/add-three-books.sql")
it's better to use `@Sql(scripts...` under the test class

2024-11-11 15:22 UTC, Elena-Bruyako commented on src/test/java/com/example/demo/controller/BookControllerTest.java
> +        CreateBookRequestDto requestDto = new CreateBookRequestDto()
suggestion, create TestUtil class and implement static methods to provide test data

2024-11-11 15:22 UTC, Elena-Bruyako commented on src/test/java/com/example/demo/controller/BookControllerTest.java
> +        Assertions.assertEquals(expected.size(), actual.size());
use static imports

2024-11-11 15:22 UTC, Elena-Bruyako commented on src/test/java/com/example/demo/controller/CategoryControllerTest.java
> +
same comments as above

2024-11-11 15:22 UTC, Elena-Bruyako commented on src/test/java/com/example/demo/service/book/BookServiceImplTest.java
> +        Book book1 = generateFirstBook();
don't use numbers for naming

2024-11-11 18:29 UTC, slava-moiseev-kramatorsk commented on src/test/java/com/example/demo/controller/BookControllerTest.java
> +@Transactional
Були трабли с білдом на гіт.Тому й додав

2024-11-12 10:59 UTC, Elena-Bruyako requested changes

2024-11-12 10:59 UTC, Elena-Bruyako commented on .env
> +MYSQLDB_ROOT_PASSWORD=rfrfirf
fix comment

2024-11-12 10:59 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Category.java
> +@RequiredArgsConstructor
entity should have default constructor 
```suggestion
@NoArgsConstructor
```

2024-11-12 10:59 UTC, Elena-Bruyako commented on src/test/java/com/example/demo/controller/BookControllerTest.java
> +    static class TestUtil {
it should be separate class

2024-11-12 10:59 UTC, Elena-Bruyako commented on src/test/java/com/example/demo/service/book/BookServiceImplTest.java
> +    private Category generateCategory() {
replace to TestUtil class and other methods also

2024-11-12 10:59 UTC, Elena-Bruyako commented on src/test/java/com/example/demo/service/category/CategoryServiceImplTest.java
> +    private CreateCategoryDto generateCategory() {
same as above

2024-11-12 10:59 UTC, Elena-Bruyako commented on src/test/resources/database/add-three-books.sql
> +INSERT INTO books (id, title, author, isbn, price) VALUES (3, 'Orange', 'Platon', '75675677', 2);
```suggestion
INSERT INTO books (id, title, author, isbn, price) 
VALUES (1, 'Testing', 'Robert', '866755', 30),
(2, 'Scream', 'Slava', '435343534', 28),
(3, 'Orange', 'Platon', '75675677', 2);
```

2024-11-12 10:59 UTC, Elena-Bruyako commented on src/test/resources/database/insert-into-categories.sql
> +INSERT INTO categories (id, name, description) VALUES (1,'Dex', 'dex books');
same here

2024-11-13 12:13 UTC, okuzan approved these changes

2024-11-13 13:01 UTC, merged