Finished task
slava-moiseev-kramatorsk/spring_boot_intro pull request #6
Opened 2024-08-03 14:39 UTC by slava-moiseev-kramatorsk

2024-08-04 12:18 UTC, slava-moiseev-kramatorsk commented
Коміт "Finish again..." - завдання Spring Boot Data JPA
Коміт "Add search functional" - завдання Add ability to search books
Ну мені поки попередне не апрувнили - зробив наступне, все в одному ПР. Не знаю чи можна так чи ні....

2024-08-04 15:11 UTC, Elena-Bruyako requested changes
Try to avoid several HWs in one PR. If you HW hasn't approved yet - ask in chat

2024-08-04 15:11 UTC, Elena-Bruyako commented on pom.xml
> +			<version>4.22.0</version>
```suggestion
			<version>${liquibase.version}</version>
```

2024-08-04 15:11 UTC, Elena-Bruyako commented on pom.xml
> +			<groupId>org.liquibase</groupId>
it should be in plugin section

2024-08-04 15:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +@Where(clause = "is_deleted=false")
`@Where` is deprecated

2024-08-04 15:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
>  @Data
Don't use `@Data` for entities

2024-08-04 15:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    @Column(name = "title", nullable = false)
```suggestion
    @Column(nullable = false)
```

2024-08-04 15:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    @Column(name = "author", nullable = false)
```suggestion
    @Column(nullable = false)
```

2024-08-04 15:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    @Column(name = "isbn", nullable = false, unique = true)
```suggestion
    @Column(nullable = false, unique = true)
```

2024-08-04 15:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    @Column(name = "price", nullable = false)
```suggestion
    @Column(nullable = false)
```

2024-08-04 15:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    @Column(name = "description")
```suggestion
```

2024-08-04 15:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    @Column(name = "cover_image")
```suggestion
```

2024-08-04 15:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/repository/book/BookSpecificationBuilder.java
> +            spec = spec.and(bookSpecificationProviderManager.getSpecificationProvider("title")
make title and author constants

2024-08-04 15:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/repository/book/spec/AuthorSpecificationProvider.java
> +        return "author";
make it constant

2024-08-04 15:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/repository/book/spec/TitleSpecificationProvider.java
> +        return "title";
make it constant

2024-08-04 15:20 UTC, slava-moiseev-kramatorsk commented on pom.xml
> +			<version>4.22.0</version>
Були трабли з створенням таблиці і було припущення, що справа у версіі. Тому постав явну версію. Помилка була в іншому, але не захотів "рементувати" те, що працює.

2024-08-04 15:28 UTC, slava-moiseev-kramatorsk commented on src/main/java/com/example/demo/model/Book.java
> +@Where(clause = "is_deleted=false")
@Where deprecated з версіі Hibernate  6.3 , а я використовую <version>6.2.7.Final</version> тому залишив @Where замість @SQLRestriction.  Та в цієї версіі такої аннотація навіть нема.

2024-08-04 15:32 UTC, slava-moiseev-kramatorsk commented on src/main/java/com/example/demo/model/Book.java
>  @Data
Оскількі поки в класі нема об'ектів які б могли викликати lazyinitializationexception вирішив залишити. Прибираю.

2024-08-04 15:33 UTC, slava-moiseev-kramatorsk commented on src/main/java/com/example/demo/model/Book.java
> +    @Column(name = "title", nullable = false)
Чьому ? якісь колонки іменуймо,якісь ні. Щоб наверняка -всі проіменував.

2024-08-05 12:54 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    @Column(name = "title", nullable = false)
Hibernate names column automatically in snake_case format

2024-08-05 12:55 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
>  @Data
It's better to write correct code straightaway to avoid fixing or refactoring in future

2024-08-05 12:56 UTC, Elena-Bruyako commented on pom.xml
> +			<version>4.22.0</version>
Bad approaches also "work well" but it doesn't mean that we should use them)

2024-08-05 12:57 UTC, Elena-Bruyako approved these changes
well done

2024-08-05 17:25 UTC, merged