Finished task? try-1
slava-moiseev-kramatorsk/spring_boot_intro pull request #7
Opened 2024-08-06 19:30 UTC by slava-moiseev-kramatorsk

В умові задачі маеться розпливчате формулювання щото валідацію ДТО - Add meaningful validation for existing DTO classes.
Зробив на свій розсуд. Доречі не розумію значення поля "isbn". Проста валідація на символи, велику літеру имя автора, обмеження по довжині.

2024-08-07 10:00 UTC, MentorMateAcademy requested changes

2024-08-07 10:00 UTC, MentorMateAcademy commented on src/main/java/com/example/demo/dto/CreateBookRequestDto.java
>      private String description;
you can validate description too

2024-08-07 10:00 UTC, MentorMateAcademy commented on src/main/java/com/example/demo/validation/IsbnBookValidator.java
> +                && inputIsbn.length() < 100;
magic number

2024-08-07 10:00 UTC, MentorMateAcademy commented on src/main/java/com/example/demo/validation/TitleValidation.java
> +        return inputTitle.matches(REGEX_TITLE) && inputTitle.length() < 50;
here too

2024-08-07 10:01 UTC, MentorMateAcademy requested changes

2024-08-07 10:01 UTC, MentorMateAcademy commented on src/main/java/com/example/demo/validation/IsbnBookValidator.java
> +                && inputIsbn.length() < 100;
you can validate length in regex

2024-08-08 12:55 UTC, okuzan approved these changes

2024-08-08 16:33 UTC, merged